version: "3.7"

services:
  local-map:
    image: node:12-alpine
    command: sh -c "npm install && npm run seed && node server/start.js"
    ports:
      - 8002:8002
    working_dir: /local-map
    volumes:
      - ./:/local-map

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

    volumes:
      - local-map:/var/lib/mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

volumes:
  local-map: