version: 2.1
jobs:
  build:
    macos:
      xcode: 11.3.1
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme circleci-demo-macos
      - run:
          name: Build Application
          command: xcodebuild
      - run:
          name: Compress app for storage
          command: zip -r app.zip build/Release/circleci-demo-macos.app
      - store_artifacts:
          path: app.zip
          destination: app
